[MRG] FIX random failure of batch pll test (#1326)
* [MRG] FIX random failure of batch pll test

This should hopefully fix the random test failures that we see
occasionally where we stochastically get a single failure from

> FAILED hnn_core/tests/test_batch_simulate.py::test_parallel_execution
- AssertionError: Parallel execution is not faster than serial
execution!

I was able to reliably reproduce this test failure on my home linux
laptop, and then able to investigate it. I first started increasing the
amount of compute work needed for both simulations, but I had to
increase it by quite a bit in order for the test to *mostly* pass. I
then asked Claude for help. It said that,
since our batch simulations are so small, and the total batch time is on
the order of 2-3 seconds, the main issue is that when `n_jobs = 1`, there is
no parallel code run at all, but when there is any parallel use, then
there is a startup cost to build the parallel process tool by Loky that
is paid the first time it sees that configuration. After running several
experiments, it found that the *first* time `n_jobs=2` is used, there is
a 0.5-1.5 second overhead cost to construct the parallel pool, but
on *subsequent* runs with `n_jobs=2`, this overhead is not paid.

Therefore, one solution (which I've implemented here) is to simply run a
parallel `n_jobs=2` case once but NOT record the time spent for
simulation, and then run it again but record only the second time it
ran. This way, the pool is already warmed and we can properly measure
the *simulation* time difference, which is the main thing we're
interested in here (not the overhead time, which will always be
approximately less than two seconds).

As I said in the comment, another way to fix this would to simply
increase the amount of compute used for the test, but not only is that
wasteful, it would also force us to run the test for longer. The current
new approach in this PR is better, because it only increases the time of
the test by however much it takes to rerun the same tiny simulations in
parallel using a warmed-up pool (which on my local machine, is usually
around 0.75 seconds).

* FIX further attempts at mitigating batch pll test

Judging from the failure of this same test over the course of #1326 (by
the time you're reading this, the logs for the failing Github Action may
have been deleted automatically), warming up the parallel pool still is
not enough to solve the problem at least for the `macos-intel-15`
runners of Github Actions, which are quite old. Whether this is an old
hardware issue or a platform-related problem with `loky`, or something
else, I'm not sure.

In response, I've also increased the length of time of the simulation as
well, and increased the parallel cores used in order to still try to get
the test to pass *reliably* on all hardware. In the Github Actions
platforms we use, we always have access to at least 3 cores:
https://docs.github.com/en/actions/reference/runners/github-hosted-runners